name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - terraform.tfvars
  pull_request:
    paths:
      - terraform.tfvars

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0 # Replace with your desired Terraform version
      - name: Configure AWS credentials
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Initialize Terraform
        run: terraform init
      - name: Validate Terraform configuration
        run: terraform validate
      - name: Create branch and pull request (if `terraform.tfvars` changed)
        run: |
          if [[ $(git diff --name-only --cached) =~ terraform\.tfvars ]]; then
            git checkout -b "update-instance-name"
            git push --set-upstream origin update-instance-name
            echo "Created branch and pull request."
          fi
      - name: Apply Terraform changes on pull request
        if: github.event_name == 'pull_request'
        run: terraform apply -auto-approve
      - name: Apply Terraform changes on push to main
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
